export const DIRECTION_LEFT = 'DIRECTION_LEFT';
export const DIRECTION_RIGHT = 'DIRECTION_RIGHT';
export const DIRECTION_UP = 'DIRECTION_UP';
export const DIRECTION_DOWN = 'DIRECTION_DOWN';

export const START_GAME = 'START_GAME';
export const END_GAME = 'END_GAME';
export const MAX_BOARD_SIZE = 25;
export const MIN_BOARD_SIZE = 10;
export const CHANGE_BOARD_SIZE = 'CHANGE_BOARD_SIZE';
export const CHANGE_DIRECTION = 'CHANGE_DIRECTION';
export const CREATE_BOARD = 'CREATE_BOARD';
export const MOVE_SNAKE = 'MOVE_SNAKE';
export const SPAWN_FOOD = 'SPAWN_FOOD';
export const EAT_FOOD = 'EAT_FOOD';
export const BOARD_SIZE = 20;
export const BOARD_EMPTY = 0;

export const OPPOSITE_DIRECTIONS = {
  DIRECTION_LEFT: DIRECTION_RIGHT,
  DIRECTION_RIGHT: DIRECTION_LEFT,
  DIRECTION_UP: DIRECTION_DOWN,
  DIRECTION_DOWN: DIRECTION_UP,
};